services:
  db:
    container_name: time-tracker-postgres
    image: postgres:16    
    ports:
    - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: time-tracker
    volumes:
      - ./migrations/postgres/init_up.sql:/docker-entrypoint-initdb.d/1-init_up.sql

  server:
    container_name: time-tracker-server
    build:
      context: ..
    restart: on-failure:3
    env_file: .env
    environment:
      DB_HOST: db
    ports:
      - ${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}
    depends_on:
      - db
